GET http://ahasmarter.com/api/v1/ycy/groups/1f423133 HTTP/1.1
GET http://ahasmarter.com/api/v1/ycy/messages HTTP/1.1
POST http://ahasmarter.com/api/v1/ycy/groups/1f423133 HTTP/1.1
content-type: application/json

{
  "name": "傻蛋"
}
POST http://127.0.0.1:4000/api/v1/ycy/users/create HTTP/1.1
content-type: application/json

{
  "users": [{"name": "傻蛋","puid": "aabbb"}, {"name": "大爷", "puid": "ddccc"}]
}